runtime: nodejs16

handlers:
- url: /.*
  script: npm start

env_variables:
  DB_USER: postgres
  DB_PASS: plants
  DB_NAME: plantsdb
  INSTANCE_CONNECTION_NAME: plantsapp-356420:us-east1:plantsdb   

# beta_settings:
#   cloud_postgresql_instances: plantsapp-356420:us-east1:plantsdb