runtime: nodejs16

handlers:
  url: /.*
  script: auto

env_variables:
  SQL_USER: postgres
  SQL_PASSWORD: plants
  SQL_DATABASE: plantsdb
  INSTANCE_CONNECTION_NAME: plantsapp-356420:us-east1:plantsdb   

beta_settings:
  cloud_postgresql_instances: plantsapp-356420:us-east1:plantsdb